import { Center, Heading, useColorMode } from '@chakra-ui/react'
import type { NextPage } from 'next'
import Head from 'next/head'
import { DarkModeSwitch } from '../components/DarkModeSwitch'
import { color } from '../theme'

const Home: NextPage = () => {
  const { colorMode } = useColorMode()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <DarkModeSwitch />
      <Center height='100vh'>
        <Heading color={color[colorMode]}>Test</Heading>
      </Center>
    </>
  )
}

export default Home
